// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $contact from "./routes/contact.tsx";
import * as $pricing from "./routes/pricing.tsx";
import * as $legal_terms from "./routes/legal/terms.tsx";
import * as $legal_privacy from "./routes/legal/privacy.tsx";
import * as $legal_cancellation from "./routes/legal/cancellation.tsx";
import * as $legal_shipping from "./routes/legal/shipping.tsx";
import * as $api_contact from "./routes/api/contact.ts";
import * as $api_scrape from "./routes/api/scrape.ts";
import * as $api_properties from "./routes/api/properties.ts";
import * as $api_pay from "./routes/api/pay.ts";
import * as $api_bookings from "./routes/api/bookings.ts";
import * as $api_verify from "./routes/api/verify.ts";
import * as $api_chat from "./routes/api/chat.ts";
import * as $api_knowledge from "./routes/api/knowledge.ts";
import * as $api_cron_sync from "./routes/api/cron/sync.ts";
import * as $api_webhooks_payment from "./routes/api/webhooks/payment.ts";
import * as $api_caretaker_supply from "./routes/api/caretaker/supply.ts";
import * as $dashboard_middleware from "./routes/dashboard/_middleware.ts";
import * as $dashboard_layout from "./routes/dashboard/_layout.tsx";
import * as $dashboard_index from "./routes/dashboard/index.tsx";
import * as $dashboard_properties from "./routes/dashboard/properties.tsx";
import * as $dashboard_knowledge from "./routes/dashboard/knowledge.tsx";
import * as $p_propId from "./routes/p/[propId].tsx";
import * as $p_checkout from "./routes/p/checkout.tsx";
import * as $care_token from "./routes/care/[token].tsx";
import * as $EarningsCalculator from "./islands/EarningsCalculator.tsx";
import * as $MobileMenu from "./islands/MobileMenu.tsx";
import * as $DashboardSidebar from "./islands/DashboardSidebar.tsx";
import * as $AddProperty from "./islands/AddProperty.tsx";
import * as $BookingCalendar from "./islands/BookingCalendar.tsx";
import * as $CheckoutForm from "./islands/CheckoutForm.tsx";
import * as $SupplyRequest from "./islands/SupplyRequest.tsx";
import * as $IdVerification from "./islands/IdVerification.tsx";
import * as $GuestChat from "./islands/GuestChat.tsx";
import * as $KnowledgeEditor from "./islands/KnowledgeEditor.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/contact.tsx": $contact,
    "./routes/pricing.tsx": $pricing,
    "./routes/legal/terms.tsx": $legal_terms,
    "./routes/legal/privacy.tsx": $legal_privacy,
    "./routes/legal/cancellation.tsx": $legal_cancellation,
    "./routes/legal/shipping.tsx": $legal_shipping,
    "./routes/api/contact.ts": $api_contact,
    "./routes/api/scrape.ts": $api_scrape,
    "./routes/api/properties.ts": $api_properties,
    "./routes/api/pay.ts": $api_pay,
    "./routes/api/bookings.ts": $api_bookings,
    "./routes/api/verify.ts": $api_verify,
    "./routes/api/chat.ts": $api_chat,
    "./routes/api/knowledge.ts": $api_knowledge,
    "./routes/api/cron/sync.ts": $api_cron_sync,
    "./routes/api/webhooks/payment.ts": $api_webhooks_payment,
    "./routes/api/caretaker/supply.ts": $api_caretaker_supply,
    "./routes/dashboard/_middleware.ts": $dashboard_middleware,
    "./routes/dashboard/_layout.tsx": $dashboard_layout,
    "./routes/dashboard/index.tsx": $dashboard_index,
    "./routes/dashboard/properties.tsx": $dashboard_properties,
    "./routes/dashboard/knowledge.tsx": $dashboard_knowledge,
    "./routes/p/[propId].tsx": $p_propId,
    "./routes/p/checkout.tsx": $p_checkout,
    "./routes/care/[token].tsx": $care_token,
  },
  islands: {
    "./islands/EarningsCalculator.tsx": $EarningsCalculator,
    "./islands/MobileMenu.tsx": $MobileMenu,
    "./islands/DashboardSidebar.tsx": $DashboardSidebar,
    "./islands/AddProperty.tsx": $AddProperty,
    "./islands/BookingCalendar.tsx": $BookingCalendar,
    "./islands/CheckoutForm.tsx": $CheckoutForm,
    "./islands/SupplyRequest.tsx": $SupplyRequest,
    "./islands/IdVerification.tsx": $IdVerification,
    "./islands/GuestChat.tsx": $GuestChat,
    "./islands/KnowledgeEditor.tsx": $KnowledgeEditor,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
