// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_auth_forgot from "./routes/api/auth/forgot.ts";
import * as $api_auth_login from "./routes/api/auth/login.ts";
import * as $api_auth_logout from "./routes/api/auth/logout.ts";
import * as $api_auth_register from "./routes/api/auth/register.ts";
import * as $api_auth_resend_verification from "./routes/api/auth/resend-verification.ts";
import * as $api_billing_pay from "./routes/api/billing/pay.ts";
import * as $api_billing_subscription from "./routes/api/billing/subscription.ts";
import * as $api_billing_verify from "./routes/api/billing/verify.ts";
import * as $api_bookings from "./routes/api/bookings.ts";
import * as $api_caretaker_ready from "./routes/api/caretaker/ready.ts";
import * as $api_caretaker_supply from "./routes/api/caretaker/supply.ts";
import * as $api_chat from "./routes/api/chat.ts";
import * as $api_contact from "./routes/api/contact.ts";
import * as $api_cron_reviews from "./routes/api/cron/reviews.ts";
import * as $api_cron_sync from "./routes/api/cron/sync.ts";
import * as $api_host_api_key_rotate from "./routes/api/host/api-key/rotate.ts";
import * as $api_host_form_c_bookingId_ from "./routes/api/host/form-c/[bookingId].ts";
import * as $api_host_team from "./routes/api/host/team.ts";
import * as $api_host_team_invite from "./routes/api/host/team/invite.ts";
import * as $api_host_webhooks_add from "./routes/api/host/webhooks/add.ts";
import * as $api_host_webhooks_remove from "./routes/api/host/webhooks/remove.ts";
import * as $api_ical_propId_ from "./routes/api/ical/[propId].ts";
import * as $api_invoice_bookingId_ from "./routes/api/invoice/[bookingId].ts";
import * as $api_knowledge from "./routes/api/knowledge.ts";
import * as $api_knowledge_ocr from "./routes/api/knowledge/ocr.ts";
import * as $api_onboard_pay from "./routes/api/onboard/pay.ts";
import * as $api_onboard_verify from "./routes/api/onboard/verify.ts";
import * as $api_pay from "./routes/api/pay.ts";
import * as $api_properties from "./routes/api/properties.ts";
import * as $api_public_listings from "./routes/api/public/listings.ts";
import * as $api_public_search from "./routes/api/public/search.ts";
import * as $api_scrape from "./routes/api/scrape.ts";
import * as $api_verify_index from "./routes/api/verify/index.ts";
import * as $api_verify_status from "./routes/api/verify/status.ts";
import * as $api_webhooks_payment from "./routes/api/webhooks/payment.ts";
import * as $api_webhooks_whatsapp from "./routes/api/webhooks/whatsapp.ts";
import * as $blog_slug_ from "./routes/blog/[slug].tsx";
import * as $blog_index from "./routes/blog/index.tsx";
import * as $care_token_ from "./routes/care/[token].tsx";
import * as $contact from "./routes/contact.tsx";
import * as $dashboard_layout from "./routes/dashboard/_layout.tsx";
import * as $dashboard_middleware from "./routes/dashboard/_middleware.ts";
import * as $dashboard_billing from "./routes/dashboard/billing.tsx";
import * as $dashboard_bookings from "./routes/dashboard/bookings.tsx";
import * as $dashboard_guests from "./routes/dashboard/guests.tsx";
import * as $dashboard_index from "./routes/dashboard/index.tsx";
import * as $dashboard_knowledge from "./routes/dashboard/knowledge.tsx";
import * as $dashboard_properties from "./routes/dashboard/properties.tsx";
import * as $dashboard_settings from "./routes/dashboard/settings.tsx";
import * as $feedback_token_ from "./routes/feedback/[token].tsx";
import * as $forgot_password from "./routes/forgot-password.tsx";
import * as $index from "./routes/index.tsx";
import * as $invoice_bookingId_ from "./routes/invoice/[bookingId].tsx";
import * as $legal_cancellation from "./routes/legal/cancellation.tsx";
import * as $legal_privacy from "./routes/legal/privacy.tsx";
import * as $legal_shipping from "./routes/legal/shipping.tsx";
import * as $legal_terms from "./routes/legal/terms.tsx";
import * as $login from "./routes/login.tsx";
import * as $p_propId_ from "./routes/p/[propId].tsx";
import * as $p_checkout from "./routes/p/checkout.tsx";
import * as $pricing from "./routes/pricing.tsx";
import * as $register from "./routes/register.tsx";
import * as $search from "./routes/search.tsx";
import * as $sitemap_xml from "./routes/sitemap.xml.ts";
import * as $verify from "./routes/verify.tsx";
import * as $widget_propId_ from "./routes/widget/[propId].tsx";
import * as $widgets_book_now_propId_ from "./routes/widgets/book-now/[propId].tsx";
import * as $AddProperty from "./islands/AddProperty.tsx";
import * as $BillingManager from "./islands/BillingManager.tsx";
import * as $BookingCalendar from "./islands/BookingCalendar.tsx";
import * as $BookingFlow from "./islands/BookingFlow.tsx";
import * as $CaretakerChecklist from "./islands/CaretakerChecklist.tsx";
import * as $CheckoutForm from "./islands/CheckoutForm.tsx";
import * as $CookieBanner from "./islands/CookieBanner.tsx";
import * as $DashboardSidebar from "./islands/DashboardSidebar.tsx";
import * as $DeveloperApi from "./islands/DeveloperApi.tsx";
import * as $EarningsCalculator from "./islands/EarningsCalculator.tsx";
import * as $EarningsComparison from "./islands/EarningsComparison.tsx";
import * as $EmbedWidgetModal from "./islands/EmbedWidgetModal.tsx";
import * as $ErrorBoundary from "./islands/ErrorBoundary.tsx";
import * as $FaqSearch from "./islands/FaqSearch.tsx";
import * as $FinancialLedger from "./islands/FinancialLedger.tsx";
import * as $ForgotPasswordForm from "./islands/ForgotPasswordForm.tsx";
import * as $GuestChat from "./islands/GuestChat.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $IdVerification from "./islands/IdVerification.tsx";
import * as $KnowledgeEditor from "./islands/KnowledgeEditor.tsx";
import * as $KnowledgeUploader from "./islands/KnowledgeUploader.tsx";
import * as $LazyIsland from "./islands/LazyIsland.tsx";
import * as $LinkPerformanceChart from "./islands/LinkPerformanceChart.tsx";
import * as $ListingCarousel from "./islands/ListingCarousel.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $MagicScraperAnimation from "./islands/MagicScraperAnimation.tsx";
import * as $MobileMenu from "./islands/MobileMenu.tsx";
import * as $OfflineNotice from "./islands/OfflineNotice.tsx";
import * as $OtaSavingsChart from "./islands/OtaSavingsChart.tsx";
import * as $PricingCheckout from "./islands/PricingCheckout.tsx";
import * as $ProofOfCleanUploader from "./islands/ProofOfCleanUploader.tsx";
import * as $PropertyGrid from "./islands/PropertyGrid.tsx";
import * as $RegisterForm from "./islands/RegisterForm.tsx";
import * as $ResendVerificationBtn from "./islands/ResendVerificationBtn.tsx";
import * as $ScraperPreview from "./islands/ScraperPreview.tsx";
import * as $ScrollToTop from "./islands/ScrollToTop.tsx";
import * as $SettingsTabs from "./islands/SettingsTabs.tsx";
import * as $SupplyRequest from "./islands/SupplyRequest.tsx";
import * as $TeamManagement from "./islands/TeamManagement.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/auth/forgot.ts": $api_auth_forgot,
    "./routes/api/auth/login.ts": $api_auth_login,
    "./routes/api/auth/logout.ts": $api_auth_logout,
    "./routes/api/auth/register.ts": $api_auth_register,
    "./routes/api/auth/resend-verification.ts": $api_auth_resend_verification,
    "./routes/api/billing/pay.ts": $api_billing_pay,
    "./routes/api/billing/subscription.ts": $api_billing_subscription,
    "./routes/api/billing/verify.ts": $api_billing_verify,
    "./routes/api/bookings.ts": $api_bookings,
    "./routes/api/caretaker/ready.ts": $api_caretaker_ready,
    "./routes/api/caretaker/supply.ts": $api_caretaker_supply,
    "./routes/api/chat.ts": $api_chat,
    "./routes/api/contact.ts": $api_contact,
    "./routes/api/cron/reviews.ts": $api_cron_reviews,
    "./routes/api/cron/sync.ts": $api_cron_sync,
    "./routes/api/host/api-key/rotate.ts": $api_host_api_key_rotate,
    "./routes/api/host/form-c/[bookingId].ts": $api_host_form_c_bookingId_,
    "./routes/api/host/team.ts": $api_host_team,
    "./routes/api/host/team/invite.ts": $api_host_team_invite,
    "./routes/api/host/webhooks/add.ts": $api_host_webhooks_add,
    "./routes/api/host/webhooks/remove.ts": $api_host_webhooks_remove,
    "./routes/api/ical/[propId].ts": $api_ical_propId_,
    "./routes/api/invoice/[bookingId].ts": $api_invoice_bookingId_,
    "./routes/api/knowledge.ts": $api_knowledge,
    "./routes/api/knowledge/ocr.ts": $api_knowledge_ocr,
    "./routes/api/onboard/pay.ts": $api_onboard_pay,
    "./routes/api/onboard/verify.ts": $api_onboard_verify,
    "./routes/api/pay.ts": $api_pay,
    "./routes/api/properties.ts": $api_properties,
    "./routes/api/public/listings.ts": $api_public_listings,
    "./routes/api/public/search.ts": $api_public_search,
    "./routes/api/scrape.ts": $api_scrape,
    "./routes/api/verify/index.ts": $api_verify_index,
    "./routes/api/verify/status.ts": $api_verify_status,
    "./routes/api/webhooks/payment.ts": $api_webhooks_payment,
    "./routes/api/webhooks/whatsapp.ts": $api_webhooks_whatsapp,
    "./routes/blog/[slug].tsx": $blog_slug_,
    "./routes/blog/index.tsx": $blog_index,
    "./routes/care/[token].tsx": $care_token_,
    "./routes/contact.tsx": $contact,
    "./routes/dashboard/_layout.tsx": $dashboard_layout,
    "./routes/dashboard/_middleware.ts": $dashboard_middleware,
    "./routes/dashboard/billing.tsx": $dashboard_billing,
    "./routes/dashboard/bookings.tsx": $dashboard_bookings,
    "./routes/dashboard/guests.tsx": $dashboard_guests,
    "./routes/dashboard/index.tsx": $dashboard_index,
    "./routes/dashboard/knowledge.tsx": $dashboard_knowledge,
    "./routes/dashboard/properties.tsx": $dashboard_properties,
    "./routes/dashboard/settings.tsx": $dashboard_settings,
    "./routes/feedback/[token].tsx": $feedback_token_,
    "./routes/forgot-password.tsx": $forgot_password,
    "./routes/index.tsx": $index,
    "./routes/invoice/[bookingId].tsx": $invoice_bookingId_,
    "./routes/legal/cancellation.tsx": $legal_cancellation,
    "./routes/legal/privacy.tsx": $legal_privacy,
    "./routes/legal/shipping.tsx": $legal_shipping,
    "./routes/legal/terms.tsx": $legal_terms,
    "./routes/login.tsx": $login,
    "./routes/p/[propId].tsx": $p_propId_,
    "./routes/p/checkout.tsx": $p_checkout,
    "./routes/pricing.tsx": $pricing,
    "./routes/register.tsx": $register,
    "./routes/search.tsx": $search,
    "./routes/sitemap.xml.ts": $sitemap_xml,
    "./routes/verify.tsx": $verify,
    "./routes/widget/[propId].tsx": $widget_propId_,
    "./routes/widgets/book-now/[propId].tsx": $widgets_book_now_propId_,
  },
  islands: {
    "./islands/AddProperty.tsx": $AddProperty,
    "./islands/BillingManager.tsx": $BillingManager,
    "./islands/BookingCalendar.tsx": $BookingCalendar,
    "./islands/BookingFlow.tsx": $BookingFlow,
    "./islands/CaretakerChecklist.tsx": $CaretakerChecklist,
    "./islands/CheckoutForm.tsx": $CheckoutForm,
    "./islands/CookieBanner.tsx": $CookieBanner,
    "./islands/DashboardSidebar.tsx": $DashboardSidebar,
    "./islands/DeveloperApi.tsx": $DeveloperApi,
    "./islands/EarningsCalculator.tsx": $EarningsCalculator,
    "./islands/EarningsComparison.tsx": $EarningsComparison,
    "./islands/EmbedWidgetModal.tsx": $EmbedWidgetModal,
    "./islands/ErrorBoundary.tsx": $ErrorBoundary,
    "./islands/FaqSearch.tsx": $FaqSearch,
    "./islands/FinancialLedger.tsx": $FinancialLedger,
    "./islands/ForgotPasswordForm.tsx": $ForgotPasswordForm,
    "./islands/GuestChat.tsx": $GuestChat,
    "./islands/Header.tsx": $Header,
    "./islands/IdVerification.tsx": $IdVerification,
    "./islands/KnowledgeEditor.tsx": $KnowledgeEditor,
    "./islands/KnowledgeUploader.tsx": $KnowledgeUploader,
    "./islands/LazyIsland.tsx": $LazyIsland,
    "./islands/LinkPerformanceChart.tsx": $LinkPerformanceChart,
    "./islands/ListingCarousel.tsx": $ListingCarousel,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/MagicScraperAnimation.tsx": $MagicScraperAnimation,
    "./islands/MobileMenu.tsx": $MobileMenu,
    "./islands/OfflineNotice.tsx": $OfflineNotice,
    "./islands/OtaSavingsChart.tsx": $OtaSavingsChart,
    "./islands/PricingCheckout.tsx": $PricingCheckout,
    "./islands/ProofOfCleanUploader.tsx": $ProofOfCleanUploader,
    "./islands/PropertyGrid.tsx": $PropertyGrid,
    "./islands/RegisterForm.tsx": $RegisterForm,
    "./islands/ResendVerificationBtn.tsx": $ResendVerificationBtn,
    "./islands/ScraperPreview.tsx": $ScraperPreview,
    "./islands/ScrollToTop.tsx": $ScrollToTop,
    "./islands/SettingsTabs.tsx": $SettingsTabs,
    "./islands/SupplyRequest.tsx": $SupplyRequest,
    "./islands/TeamManagement.tsx": $TeamManagement,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
